[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
rustflags = ["-Ctarget-feature=+avx2,+fma", "-Ctarget-cpu=native"]

[target.'cfg(target_arch = "arm")']
rustflags = ["-C target-feature=+v7,+neon"]
